#include <furi.h>
#include <gui/gui.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/submenu.h>
#include <furi_hal.h>
#include "notes.h"
#include <string.h>
#include <gui/elements.h>

#define TAG "flipper_tuner_app"

/* generated by fbt from .png files in images folder */
#include <flipper_tuner_icons.h>

//// Enum/struct setups

// Scenes
typedef enum {
    FlipperTunerMainMenuScene,
    FlipperTunerPlayToneScene,
    FlipperTunerMetronomeScene,
    FlipperTunerSceneCount,
} FlipperTunerScene;

// Views
typedef enum {
    FlipperTunerSubmenuView,
    FlipperTunerPlayToneView,
    FlipperTunerMetronomeView,
} FlipperTunerView;

typedef struct TunerState {
    float volume;
    bool is_playing;
    NOTE current_note;
    int current_note_index;
    FuriString* current_noteLabel;
} TunerState;

typedef struct MetronomeState {
    int bpm;
    bool is_playing;
    NOTE accent_note;
    NOTE normal_note;
    int current_beat_count;
    FuriTimer* timer;
} MetronomeState;

// App object struct
typedef struct App {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Submenu* submenu;
    View* play_tone_view;
    TunerState* tuner_state;
    View* metronome_view;
    MetronomeState* metronome_state;
} App;

typedef enum {
    FlipperTunerMainMenuScenePlayTone,
    FlipperTunerMainMenuSceneMetronome,
} FlipperTunerMainMenuSceneIndex;

typedef enum {
    FlipperTunerMainMenuScenePlayToneEvent,
    FlipperTunerMainMenuSceneMetronomeEvent,
} FlipperTunerMainMenuEvent;

int get_tunings_size() {
    return (sizeof(tunings) / sizeof(tunings[0]));
}

void flipper_tuner_menu_callback(void* context, uint32_t index) {
    App* app = context;
    switch(index) {
    case FlipperTunerMainMenuScenePlayTone:
        scene_manager_handle_custom_event(
            app->scene_manager, FlipperTunerMainMenuScenePlayToneEvent);
        break;
    case FlipperTunerMainMenuSceneMetronome:
        scene_manager_handle_custom_event(
            app->scene_manager, FlipperTunerMainMenuSceneMetronomeEvent);
        break;
    }
}

// Main Menu scene
void flipper_tuner_main_menu_scene_on_enter(void* context) {
    App* app = context;
    submenu_reset(app->submenu); // Reset submenu
    submenu_set_header(app->submenu, "Flipper Tuner"); // Set header
    submenu_add_item(
        app->submenu,
        "Play Tone",
        FlipperTunerMainMenuScenePlayTone,
        flipper_tuner_menu_callback,
        app);
    submenu_add_item(
        app->submenu,
        "Metronome",
        FlipperTunerMainMenuSceneMetronome,
        flipper_tuner_menu_callback,
        app);
    view_dispatcher_switch_to_view(app->view_dispatcher, FlipperTunerSubmenuView);
}
bool flipper_tuner_main_menu_scene_on_event(void* context, SceneManagerEvent event) {
    App* app = context;
    bool consumed = false;

    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case FlipperTunerMainMenuScenePlayToneEvent:
            scene_manager_next_scene(app->scene_manager, FlipperTunerPlayToneScene);
            consumed = true;
            break;
        case FlipperTunerMainMenuSceneMetronomeEvent:
            scene_manager_next_scene(app->scene_manager, FlipperTunerMetronomeScene);
            consumed = true;
            break;
        }
        break;
    default:
        break;
    }
    return consumed;
}
void flipper_tuner_main_menu_scene_on_exit(void* context) {
    App* app = context;
    submenu_reset(app->submenu);
}

void play(App* app, bool is_tuner) {
    if(furi_hal_speaker_is_mine() || furi_hal_speaker_acquire(1000)) {
        if(is_tuner) {
            TunerState* tuner_state = app->tuner_state;
            furi_hal_speaker_start(tuner_state->current_note.frequency, tuner_state->volume);
            tuner_state->is_playing = true;
        } else {
            MetronomeState* metronome_state = app->metronome_state;
            if(metronome_state->current_beat_count == 1) {
                furi_hal_speaker_start(app->metronome_state->accent_note.frequency, 1);
            } else {
                furi_hal_speaker_start(app->metronome_state->normal_note.frequency, 1);
            }
        }
    }
}

void stop(App* app, bool is_tuner) {
    if(furi_hal_speaker_is_mine()) {
        furi_hal_speaker_stop();
        furi_hal_speaker_release();
        if(is_tuner) {
            app->tuner_state->is_playing = false;
        }
    }
}

void restart(App* app, bool is_tuner) {
    if(is_tuner) {
        if(app->tuner_state->is_playing) {
            stop(app, true);
            play(app, true);
        }
    }
}

void tuner_increase_volume(TunerState* tuner_state) {
    if(tuner_state->volume < 1.0f) {
        tuner_state->volume += 0.1f;
    }
}

void tuner_decrease_volume(TunerState* tuner_state) {
    if(tuner_state->volume > 0.0f) {
        tuner_state->volume -= 0.1f;
    }
}

void tuner_increase_frequency(TunerState* tuner_state, int semitones) {
    if(tuner_state->current_note_index + semitones < get_tunings_size()) {
        tuner_state->current_note_index += semitones;
        tuner_state->current_note = tunings[tuner_state->current_note_index];
    }
}

void tuner_decrease_frequency(TunerState* tuner_state, int semitones) {
    if(tuner_state->current_note_index - semitones >= 0) {
        tuner_state->current_note_index -= semitones;
        tuner_state->current_note = tunings[tuner_state->current_note_index];
    }
}

// Play tone scene
static bool play_tone_input_callback(InputEvent* event, void* context) {
    App* app = context;
    TunerState* tuner_state = app->tuner_state;
    bool consumed = false;

    if(event->type == InputTypeShort) {
        // Stop/start
        switch(event->key) {
        case InputKeyOk:
            if(!tuner_state->is_playing) {
                play(app, true);
            } else {
                stop(app, true);
            }
            break;
        case InputKeyUp:
            tuner_increase_volume(tuner_state);
            restart(app, true);
            break;
        case InputKeyDown:
            tuner_decrease_volume(tuner_state);
            restart(app, true);
            break;
        case InputKeyLeft:
            tuner_decrease_frequency(tuner_state, 1);
            restart(app, true);
            break;
        case InputKeyRight:
            tuner_increase_frequency(tuner_state, 1);
            restart(app, true);
            break;
        case InputKeyBack:
            scene_manager_handle_back_event(app->scene_manager);
            break;
        default:
            break;
        }
        consumed = true;
    } else if(event->type == InputTypeLong) {
        switch(event->key) {
        case InputKeyUp:
            tuner_state->volume = 1;
            restart(app, true);
            break;
        case InputKeyDown:
            tuner_state->volume = 0;
            restart(app, true);
            break;
        case InputKeyLeft:
            tuner_decrease_frequency(tuner_state, 12);
            restart(app, true);
            break;
        case InputKeyRight:
            tuner_increase_frequency(tuner_state, 12);
            restart(app, true);
            break;
        case InputKeyBack:
            scene_manager_handle_back_event(app->scene_manager);
            break;
        default:
            break;
        }
        consumed = true;
    }

    with_view_model(
        app->play_tone_view,
        TunerState * model,
        { UNUSED(model); },
        true); // Call to update view
    return consumed;
}

void play_tone_view_draw_callback(Canvas* canvas, void* model) {
    furi_assert(model);
    TunerState* tuner_state = model;

    canvas_draw_frame(canvas, 0, 0, 128, 64);
    canvas_set_font(canvas, FontPrimary);

    FuriString* info = furi_string_alloc();

    // Draw note label
    furi_string_printf(info, "< %s >", tuner_state->current_note.label);
    canvas_draw_str_aligned(canvas, 64, 26, AlignCenter, AlignCenter, furi_string_get_cstr(info));

    // Draw volume
    int volumePercent = (int)round(tuner_state->volume * 100);
    furi_string_printf(info, "Volume: %d%%", volumePercent);
    canvas_draw_str_aligned(canvas, 64, 36, AlignCenter, AlignCenter, furi_string_get_cstr(info));

    furi_string_free(info);

    // Draw controls
    canvas_set_font(canvas, FontSecondary);
    tuner_state->is_playing ? elements_button_center(canvas, "Stop") :
                              elements_button_center(canvas, "Play");
    elements_button_right(canvas, "Note ^");
    elements_button_left(canvas, "Note v");
    elements_button_down(canvas, "Vol v");
    elements_button_up(canvas, "Vol ^");
}

void flipper_tuner_play_tone_scene_on_enter(void* context) {
    App* app = context;
    view_dispatcher_switch_to_view(app->view_dispatcher, FlipperTunerPlayToneView);
}
bool flipper_tuner_play_tone_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}
void flipper_tuner_play_tone_scene_on_exit(void* context) {
    App* app = context;
    if(app->tuner_state->is_playing) {
        stop(app, true);
    }
}

void metronome_timer_callback(void* context) {
    App* app = context;

    // Beep
    play(app, false);
    furi_delay_ms(50);
    stop(app, false);

    // Increase beat count
    if(app->metronome_state->current_beat_count == 4) {
        app->metronome_state->current_beat_count = 1; // Reset
    } else {
        app->metronome_state->current_beat_count += 1;
    }
}

static uint32_t state_to_sleep_ticks(MetronomeState* metronome_state) {
    // calculate time between beeps
    uint32_t tps = furi_kernel_get_tick_frequency();
    double multiplier = 4.0 / 4;
    double bps = (double)metronome_state->bpm / 60;
    return (uint32_t)(round(tps / bps) - ((50 / 1000) * tps)) * multiplier; // 50: beep length
}

void restart_timer(MetronomeState* metronome_state) {
    if(furi_timer_is_running(metronome_state->timer)) {
        furi_timer_stop(metronome_state->timer);
        furi_timer_start(metronome_state->timer, state_to_sleep_ticks(metronome_state));
    }
}

void increase_bpm(MetronomeState* metronome_state, int amount) {
    metronome_state->bpm += amount;
    restart_timer(metronome_state);
}

void decrease_bpm(MetronomeState* metronome_state, int amount) {
    metronome_state->bpm -= amount;
    restart_timer(metronome_state);
}

static bool metronome_input_callback(InputEvent* event, void* context) {
    App* app = context;
    MetronomeState* metronome_state = app->metronome_state;

    bool consumed = false;

    if(event->type == InputTypeShort) {
        switch(event->key) {
        case InputKeyOk:
            metronome_state->is_playing = !metronome_state->is_playing;
            metronome_state->is_playing ?
                furi_timer_start(metronome_state->timer, state_to_sleep_ticks(metronome_state)) :
                furi_timer_stop(metronome_state->timer);
            break;
        case InputKeyUp:
            increase_bpm(metronome_state, 1);
            break;
        case InputKeyDown:
            decrease_bpm(metronome_state, 1);
            break;
        case InputKeyBack:
            scene_manager_handle_back_event(app->scene_manager);
            break;
        default:
            break;
        }
        consumed = true;
    } else if(event->type == InputTypeLong) {
        switch(event->key) {
        case InputKeyUp:
            increase_bpm(metronome_state, 10);
            break;
        case InputKeyDown:
            decrease_bpm(metronome_state, 10);
            break;
        default:
            break;
        }
        consumed = true;
    }
    with_view_model(
        app->metronome_view,
        MetronomeState * model,
        { UNUSED(model); },
        true); // Call to update view

    return consumed;
}

void metronome_view_draw_callback(Canvas* canvas, void* model) {
    furi_assert(model);
    MetronomeState* metronome_state = model;

    canvas_draw_frame(canvas, 0, 0, 128, 64);
    canvas_set_font(canvas, FontPrimary);

    FuriString* info = furi_string_alloc();
    furi_string_printf(info, "BPM: %d", metronome_state->bpm);
    canvas_draw_str_aligned(canvas, 64, 26, AlignCenter, AlignCenter, furi_string_get_cstr(info));
    furi_string_free(info);

    // Draw controls
    canvas_set_font(canvas, FontSecondary);
    metronome_state->is_playing ? elements_button_center(canvas, "Stop") :
                                  elements_button_center(canvas, "Play");
    elements_button_up(canvas, "BPM ^");
    elements_button_down(canvas, "BPM v");
    elements_progress_bar(canvas, 28, 36, 72, (double)metronome_state->current_beat_count / 4);
}

void flipper_tuner_metronome_scene_on_enter(void* context) {
    App* app = context;
    view_dispatcher_switch_to_view(app->view_dispatcher, FlipperTunerMetronomeView);
}
bool flipper_tuner_metronome_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}
void flipper_tuner_metronome_scene_on_exit(void* context) {
    App* app = context;
    if(furi_timer_is_running(app->metronome_state->timer)) {
        furi_timer_stop(app->metronome_state->timer);
        app->metronome_state->is_playing = false;
    }
}

/// handler arrays must be in same order as scenes enum
// on_enter handlers
void (*const flipper_tuner_scene_on_enter_handlers[])(void*) = {
    flipper_tuner_main_menu_scene_on_enter,
    flipper_tuner_play_tone_scene_on_enter,
    flipper_tuner_metronome_scene_on_enter,
};

// on_event handlers
bool (*const flipper_tuner_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    flipper_tuner_main_menu_scene_on_event,
    flipper_tuner_play_tone_scene_on_event,
    flipper_tuner_metronome_scene_on_event,
};

// on_exit handlers
void (*const flipper_tuner_scene_on_exit_handlers[])(void*) = {
    flipper_tuner_main_menu_scene_on_exit,
    flipper_tuner_play_tone_scene_on_exit,
    flipper_tuner_metronome_scene_on_exit,
};

// scene manager handler object
static const SceneManagerHandlers flipper_tuner_scene_manager_handlers = {
    .on_enter_handlers = flipper_tuner_scene_on_enter_handlers,
    .on_event_handlers = flipper_tuner_scene_on_event_handlers,
    .on_exit_handlers = flipper_tuner_scene_on_exit_handlers,
    .scene_num = FlipperTunerSceneCount,
};

// Handles custom events like timer, GPIO pins
static bool basic_scene_custom_callback(void* context, uint32_t custom_event) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

bool basic_scene_back_event_callback(void* context) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

// Memory allocation
static void play_tone_alloc(void* context) {
    App* app = context;

    app->play_tone_view = view_alloc();

    view_set_draw_callback(app->play_tone_view, play_tone_view_draw_callback);
    view_allocate_model(app->play_tone_view, ViewModelTypeLockFree, sizeof(TunerState));
    app->tuner_state = view_get_model(app->play_tone_view);

    app->tuner_state->current_note_index = 57; // A4
    app->tuner_state->current_note = tunings[app->tuner_state->current_note_index];
    app->tuner_state->volume = 1.0f;
    app->tuner_state->is_playing = false;

    view_set_input_callback(app->play_tone_view, play_tone_input_callback);
    view_set_context(app->play_tone_view, app);

    view_dispatcher_add_view(app->view_dispatcher, FlipperTunerPlayToneView, app->play_tone_view);
}

static void metronome_alloc(void* context) {
    App* app = context;

    app->metronome_view = view_alloc();

    view_set_draw_callback(app->metronome_view, metronome_view_draw_callback);
    view_allocate_model(app->metronome_view, ViewModelTypeLockFree, sizeof(MetronomeState));
    app->metronome_state = view_get_model(app->metronome_view);

    app->metronome_state->bpm = 120;
    app->metronome_state->accent_note = tunings[69]; // A5
    app->metronome_state->normal_note = tunings[57]; // A4
    app->metronome_state->is_playing = false;
    app->metronome_state->current_beat_count = 1;
    app->metronome_state->timer =
        furi_timer_alloc(metronome_timer_callback, FuriTimerTypePeriodic, app);

    view_set_input_callback(app->metronome_view, metronome_input_callback);
    view_set_context(app->metronome_view, app);

    view_dispatcher_add_view(app->view_dispatcher, FlipperTunerMetronomeView, app->metronome_view);
}

static App* app_alloc() {
    App* app = malloc(sizeof(App));
    app->scene_manager = scene_manager_alloc(&flipper_tuner_scene_manager_handlers, app);
    app->view_dispatcher = view_dispatcher_alloc();

    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, basic_scene_custom_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, basic_scene_back_event_callback);

    // Submenu view
    app->submenu = submenu_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, FlipperTunerSubmenuView, submenu_get_view(app->submenu));

    play_tone_alloc(app);

    metronome_alloc(app);

    return app;
}

static void app_free(App* app) {
    furi_assert(app);

    // Remove views
    view_dispatcher_remove_view(app->view_dispatcher, FlipperTunerSubmenuView);
    view_dispatcher_remove_view(app->view_dispatcher, FlipperTunerPlayToneView);
    view_dispatcher_remove_view(app->view_dispatcher, FlipperTunerMetronomeView);

    // Memory free
    scene_manager_free(app->scene_manager);
    view_dispatcher_free(app->view_dispatcher);
    submenu_free(app->submenu);

    view_free(app->play_tone_view);
    free(app->tuner_state);

    view_free(app->metronome_view);
    //furi_timer_free(app->metronome_state->timer);
    free(app->metronome_state);
    free(app);
}

int32_t flipper_tuner_app(void* p) {
    UNUSED(p);
    App* app = app_alloc();

    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(
        app->view_dispatcher, gui, ViewDispatcherTypeFullscreen); // Initialize GUI
    scene_manager_next_scene(app->scene_manager, FlipperTunerMainMenuScene); // Begin at main menu
    view_dispatcher_run(app->view_dispatcher);

    app_free(app);
    return 0;
}
