#include <furi.h>
#include <gui/gui.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/widget.h>
#include <gui/modules/submenu.h>
#include <gui/modules/text_input.h>
#include <furi_hal.h>

#define TAG "flipper_tuner_app"

/* generated by fbt from .png files in images folder */
#include <flipper_tuner_icons.h>

//// Enum/struct setups

// Scenes
typedef enum {
    FlipperTunerMainMenuScene,
    FlipperTunerPlayToneScene,
    FlipperTunerSaveTuningScene,
    FlipperTunerLoadTuningScene,
    FlipperTunerSceneCount,
} FlipperTunerScene;

// Views
typedef enum {
    FlipperTunerSubmenuView,
    FlipperTunerWidgetView,
    FlipperTunerTextInputView,
    FlipperTunerPlayToneView,
} FlipperTunerView;

// App object struct
typedef struct App {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Submenu* submenu;
    Widget* widget;
    TextInput* text_input;
    View* play_tone_view;
} App;

typedef enum {
    FlipperTunerMainMenuScenePlayTone,
    FlipperTunerMainMenuSceneSaveTuning,
    FlipperTunerMainMenuSceneLoadTuning,
} FlipperTunerMainMenuSceneIndex;

typedef enum {
    FlipperTunerMainMenuScenePlayToneEvent,
    FlipperTunerMainMenuSceneSaveTuningEvent,
    FlipperTunerMainMenuSceneLoadTuningEvent,
} FlipperTunerMainMenuEvent;

void flipper_tuner_menu_callback(void* context, uint32_t index) {
    App* app = context;
    switch(index) {
    case FlipperTunerMainMenuScenePlayTone:
        scene_manager_handle_custom_event(
            app->scene_manager, FlipperTunerMainMenuScenePlayToneEvent);
        break;
    case FlipperTunerMainMenuSceneSaveTuning:
        scene_manager_handle_custom_event(
            app->scene_manager, FlipperTunerMainMenuSceneSaveTuningEvent);
        break;
    case FlipperTunerMainMenuSceneLoadTuning:
        scene_manager_handle_custom_event(
            app->scene_manager, FlipperTunerMainMenuSceneLoadTuningEvent);
        break;
    }
}

// Main Menu scene
void flipper_tuner_main_menu_scene_on_enter(void* context) {
    FURI_LOG_I(TAG, "main menu reached!");

    App* app = context;
    submenu_reset(app->submenu); // Reset submenu
    submenu_set_header(app->submenu, "Flipper Tuner"); // Set header
    submenu_add_item(
        app->submenu,
        "Play Tone",
        FlipperTunerMainMenuScenePlayTone,
        flipper_tuner_menu_callback,
        app);
    submenu_add_item(
        app->submenu,
        "Save New Tuning",
        FlipperTunerMainMenuSceneSaveTuning,
        flipper_tuner_menu_callback,
        app);
    submenu_add_item(
        app->submenu,
        "Load Tuning",
        FlipperTunerMainMenuSceneLoadTuning,
        flipper_tuner_menu_callback,
        app);
    view_dispatcher_switch_to_view(app->view_dispatcher, FlipperTunerSubmenuView);
}
bool flipper_tuner_main_menu_scene_on_event(void* context, SceneManagerEvent event) {
    App* app = context;
    bool consumed = false;

    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case FlipperTunerMainMenuScenePlayToneEvent:
            scene_manager_next_scene(app->scene_manager, FlipperTunerPlayToneScene);
            consumed = true;
            break;
        case FlipperTunerMainMenuSceneSaveTuningEvent:
            scene_manager_next_scene(app->scene_manager, FlipperTunerSaveTuningScene);
            consumed = true;
            break;
        case FlipperTunerMainMenuSceneLoadTuningEvent:
            scene_manager_next_scene(app->scene_manager, FlipperTunerLoadTuningScene);
            consumed = true;
            break;
        }
        break;
    default:
        break;
    }
    return consumed;
}
void flipper_tuner_main_menu_scene_on_exit(void* context) {
    App* app = context;
    submenu_reset(app->submenu);
}

typedef struct Tuner {
    View* view;
} Tuner;

typedef struct TunerState {
    float frequency;
    float volume;
    bool isPlaying;
} TunerState;

// TODO: create struct to store tuning fork state (volume, frequency, is playing) in App
void play() {
    if(furi_hal_speaker_is_mine() || furi_hal_speaker_acquire(1000)) {
        furi_hal_speaker_start(65.41, 50);
    }
}
void stop() {
    if(furi_hal_speaker_is_mine()) {
        furi_hal_speaker_stop();
        furi_hal_speaker_release();
    }
}

// Play tone scene
bool play_tone_input_callback(InputEvent* event, void* context) {
    Tuner* tuner = context;
    bool consumed = false;

    if(event->type == InputTypeShort) {
        if(event->key == InputKeyOk) {
            with_view_model(
                tuner->view,
                TunerState * model,
                {
                    if(!model.isPlaying) {
                        play();
                        model.isPlaying = true;
                    } else {
                        stop();
                        mode.isPlaying = false;
                    }
                },
                true);
            FURI_LOG_I(TAG, "ok key pressed");
        }
    }

    return consumed;
}
void play_tone_view_draw_callback(Canvas* canvas, void* model) {
    UNUSED(model);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str_aligned(canvas, 35, 42, AlignCenter, AlignCenter, "Testing");
}

void flipper_tuner_play_tone_scene_on_enter(void* context) {
    App* app = context;
    view_dispatcher_switch_to_view(app->view_dispatcher, FlipperTunerPlayToneView);
}
bool flipper_tuner_play_tone_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}
void flipper_tuner_play_tone_scene_on_exit(void* context) {
    UNUSED(context);
}

void flipper_tuner_save_tuning_scene_on_enter(void* context) {
    UNUSED(context);
}
bool flipper_tuner_save_tuning_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}
void flipper_tuner_save_tuning_scene_on_exit(void* context) {
    UNUSED(context);
}

void flipper_tuner_load_tuning_scene_on_enter(void* context) {
    UNUSED(context);
}
bool flipper_tuner_load_tuning_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}
void flipper_tuner_load_tuning_scene_on_exit(void* context) {
    UNUSED(context);
}

/// handler arrays must be in same order as scenes enum
// on_enter handlers
void (*const flipper_tuner_scene_on_enter_handlers[])(void*) = {
    flipper_tuner_main_menu_scene_on_enter,
    flipper_tuner_play_tone_scene_on_enter,
    flipper_tuner_save_tuning_scene_on_enter,
    flipper_tuner_load_tuning_scene_on_enter,
};

// on_event handlers
bool (*const flipper_tuner_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    flipper_tuner_main_menu_scene_on_event,
    flipper_tuner_play_tone_scene_on_event,
    flipper_tuner_save_tuning_scene_on_event,
    flipper_tuner_load_tuning_scene_on_event,
};

// on_exit handlers
void (*const flipper_tuner_scene_on_exit_handlers[])(void*) = {
    flipper_tuner_main_menu_scene_on_exit,
    flipper_tuner_play_tone_scene_on_exit,
    flipper_tuner_save_tuning_scene_on_exit,
    flipper_tuner_load_tuning_scene_on_exit,
};

// scene manager handler object
static const SceneManagerHandlers flipper_tuner_scene_manager_handlers = {
    .on_enter_handlers = flipper_tuner_scene_on_enter_handlers,
    .on_event_handlers = flipper_tuner_scene_on_event_handlers,
    .on_exit_handlers = flipper_tuner_scene_on_exit_handlers,
    .scene_num = FlipperTunerSceneCount,
};

// Handles custom events like timer, GPIO pins
static bool basic_scene_custom_callback(void* context, uint32_t custom_event) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

bool basic_scene_back_event_callback(void* context) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

// Memory allocation for app
static App* app_alloc() {
    App* app = malloc(sizeof(App));
    app->scene_manager = scene_manager_alloc(&flipper_tuner_scene_manager_handlers, app);
    app->view_dispatcher = view_dispatcher_alloc();

    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, basic_scene_custom_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, basic_scene_back_event_callback);

    // Submenu view
    app->submenu = submenu_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, FlipperTunerSubmenuView, submenu_get_view(app->submenu));

    // Widget view
    app->widget = widget_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, FlipperTunerWidgetView, widget_get_view(app->widget));

    // Text input view
    app->text_input = text_input_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, FlipperTunerTextInputView, text_input_get_view(app->text_input));

    // Play Tone view
    app->play_tone_view = view_alloc();
    view_set_draw_callback(app->play_tone_view, play_tone_view_draw_callback);
    view_set_input_callback(app->play_tone_view, play_tone_input_callback);
    view_dispatcher_add_view(app->view_dispatcher, FlipperTunerPlayToneView, app->play_tone_view);

    Tuner* tuner = malloc(sizeof(Tuner));
    view_set_context(tuner->view, tuner);
    view_allocate_model(tuner->view, ViewModelTypeLockFree, sizeof(TunerState));

    return app;
}

static void app_free(App* app) {
    furi_assert(app);

    // Remove views
    view_dispatcher_remove_view(app->view_dispatcher, FlipperTunerSubmenuView);
    view_dispatcher_remove_view(app->view_dispatcher, FlipperTunerWidgetView);
    view_dispatcher_remove_view(app->view_dispatcher, FlipperTunerTextInputView);
    view_dispatcher_remove_view(app->view_dispatcher, FlipperTunerPlayToneView);

    // Memory free
    scene_manager_free(app->scene_manager);
    view_dispatcher_free(app->view_dispatcher);
    submenu_free(app->submenu);
    widget_free(app->widget);
    text_input_free(app->text_input);
    view_free(app->play_tone_view);
    free(app);
}

int32_t flipper_tuner_app(void* p) {
    UNUSED(p);
    App* app = app_alloc();

    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(
        app->view_dispatcher, gui, ViewDispatcherTypeFullscreen); // Initialize GUI
    scene_manager_next_scene(app->scene_manager, FlipperTunerMainMenuScene); // Begin at main menu
    view_dispatcher_run(app->view_dispatcher);

    app_free(app);
    return 0;
}

// Scenes enum
// Views enum
// index enum??
// event enums??
// menu callback function
// _on_enter, _on_event, _on_exit functions for each scene
// _on_enter_handlers, _on_event_handlers, _on_exit_handlers arrays
// SceneManagerHandlers object
// _custom_callback function
// _back_event_callback function
// app_alloc function
// app_free function
// app function