#include <furi.h>
#include <gui/gui.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/submenu.h>
#include <furi_hal.h>
#include "notes.h"
#include <string.h>
#include <gui/elements.h>

#define TAG "flipper_tuner_app"

/* generated by fbt from .png files in images folder */
#include <flipper_tuner_icons.h>

//// Enum/struct setups

// Scenes
typedef enum {
    FlipperTunerMainMenuScene,
    FlipperTunerPlayToneScene,
    FlipperTunerMetronomeScene,
    FlipperTunerSceneCount,
} FlipperTunerScene;

// Views
typedef enum {
    FlipperTunerSubmenuView,
    FlipperTunerPlayToneView,
    FlipperTunerMetronomeView,
} FlipperTunerView;

typedef struct TunerState {
    float volume;
    bool isPlaying;
    NOTE currentNote;
    int currentNoteIndex;
    FuriString* currentNoteLabel;
} TunerState;

typedef struct MetronomeState {
    int bpm;
    bool isPlaying;
    float pitch;
} MetronomeState;

// App object struct
typedef struct App {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Submenu* submenu;
    View* play_tone_view;
    TunerState* tuner_state;
    View* metronome_view;
    MetronomeState* metronome_state;
} App;

typedef enum {
    FlipperTunerMainMenuScenePlayTone,
    FlipperTunerMainMenuSceneMetronome,
} FlipperTunerMainMenuSceneIndex;

typedef enum {
    FlipperTunerMainMenuScenePlayToneEvent,
    FlipperTunerMainMenuSceneMetronomeEvent,
} FlipperTunerMainMenuEvent;

int get_tunings_size() {
    return (sizeof(tunings) / sizeof(tunings[0]));
}

void flipper_tuner_menu_callback(void* context, uint32_t index) {
    App* app = context;
    switch(index) {
    case FlipperTunerMainMenuScenePlayTone:
        scene_manager_handle_custom_event(
            app->scene_manager, FlipperTunerMainMenuScenePlayToneEvent);
        break;
    case FlipperTunerMainMenuSceneMetronome:
        scene_manager_handle_custom_event(
            app->scene_manager, FlipperTunerMainMenuSceneMetronomeEvent);
        break;
    }
}

// Main Menu scene
void flipper_tuner_main_menu_scene_on_enter(void* context) {
    App* app = context;
    submenu_reset(app->submenu); // Reset submenu
    submenu_set_header(app->submenu, "Flipper Tuner"); // Set header
    submenu_add_item(
        app->submenu,
        "Play Tone",
        FlipperTunerMainMenuScenePlayTone,
        flipper_tuner_menu_callback,
        app);
    submenu_add_item(
        app->submenu,
        "Metronome",
        FlipperTunerMainMenuSceneMetronome,
        flipper_tuner_menu_callback,
        app);
    view_dispatcher_switch_to_view(app->view_dispatcher, FlipperTunerSubmenuView);
}
bool flipper_tuner_main_menu_scene_on_event(void* context, SceneManagerEvent event) {
    App* app = context;
    bool consumed = false;

    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case FlipperTunerMainMenuScenePlayToneEvent:
            scene_manager_next_scene(app->scene_manager, FlipperTunerPlayToneScene);
            consumed = true;
            break;
        case FlipperTunerMainMenuSceneMetronomeEvent:
            scene_manager_next_scene(app->scene_manager, FlipperTunerMetronomeScene);
            consumed = true;
            break;
        }
        break;
    default:
        break;
    }
    return consumed;
}
void flipper_tuner_main_menu_scene_on_exit(void* context) {
    App* app = context;
    submenu_reset(app->submenu);
}

void play(TunerState* tunerState) {
    if(furi_hal_speaker_is_mine() || furi_hal_speaker_acquire(1000)) {
        furi_hal_speaker_start(tunerState->currentNote.frequency, tunerState->volume);
        tunerState->isPlaying = true;
    }
}
void stop(TunerState* tunerState) {
    if(furi_hal_speaker_is_mine()) {
        furi_hal_speaker_stop();
        furi_hal_speaker_release();
        tunerState->isPlaying = false;
    }
}

void restart_player(TunerState* tunerState) {
    if(tunerState->isPlaying) {
        stop(tunerState);
        play(tunerState);
    }
}

void increase_volume(TunerState* tunerState) {
    if(tunerState->volume < 1.0f) {
        tunerState->volume += 0.1f;
    }
}

void decrease_volume(TunerState* tunerState) {
    if(tunerState->volume > 0.0f) {
        tunerState->volume -= 0.1f;
    }
}

void increase_frequency(TunerState* tunerState, int semitones) {
    if(tunerState->currentNoteIndex + semitones < get_tunings_size()) {
        tunerState->currentNoteIndex += semitones;
        tunerState->currentNote = tunings[tunerState->currentNoteIndex];
    }
}

void decrease_frequency(TunerState* tunerState, int semitones) {
    if(tunerState->currentNoteIndex - semitones >= 0) {
        tunerState->currentNoteIndex -= semitones;
        tunerState->currentNote = tunings[tunerState->currentNoteIndex];
    }
}

// Play tone scene
static bool play_tone_input_callback(InputEvent* event, void* context) {
    App* app = context;
    TunerState* tunerState = app->tuner_state;
    bool consumed = false;

    if(event->type == InputTypeShort) {
        // Stop/start
        switch(event->key) {
        case InputKeyOk:
            if(!tunerState->isPlaying) {
                play(tunerState);
            } else {
                stop(tunerState);
            }
            break;
        case InputKeyUp:
            increase_volume(tunerState);
            restart_player(tunerState);
            break;
        case InputKeyDown:
            decrease_volume(tunerState);
            restart_player(tunerState);
            break;
        case InputKeyLeft:
            decrease_frequency(tunerState, 1);
            restart_player(tunerState);
            break;
        case InputKeyRight:
            increase_frequency(tunerState, 1);
            restart_player(tunerState);
            break;
        case InputKeyBack:
            scene_manager_handle_back_event(app->scene_manager);
            break;
        default:
            break;
        }
        with_view_model(
            app->play_tone_view,
            TunerState * model,
            { UNUSED(model); },
            true); // Call to update view
        consumed = true;
    } else if(event->type == InputTypeLong) {
        switch(event->key) {
        case InputKeyUp:
            tunerState->volume = 1;
            restart_player(tunerState);
            break;
        case InputKeyDown:
            tunerState->volume = 0;
            restart_player(tunerState);
            break;
        case InputKeyLeft:
            decrease_frequency(tunerState, 12);
            restart_player(tunerState);
            break;
        case InputKeyRight:
            increase_frequency(tunerState, 12);
            restart_player(tunerState);
            break;
        case InputKeyBack:
            scene_manager_handle_back_event(app->scene_manager);
            break;
        default:
            break;
        }
        with_view_model(
            app->play_tone_view,
            TunerState * model,
            { UNUSED(model); },
            true); // Call to update view
        consumed = true;
    }
    return consumed;
}

void play_tone_view_draw_callback(Canvas* canvas, void* model) {
    furi_assert(model);
    TunerState* tunerState = model;

    canvas_draw_frame(canvas, 0, 0, 128, 64);
    canvas_set_font(canvas, FontPrimary);

    FuriString* info = furi_string_alloc();

    // Draw note label
    furi_string_printf(info, "< %s >", tunerState->currentNote.label);
    canvas_draw_str_aligned(canvas, 64, 26, AlignCenter, AlignCenter, furi_string_get_cstr(info));

    // Draw volume
    int volumePercent = (int)round(tunerState->volume * 100);
    furi_string_printf(info, "Volume: %d%%", volumePercent);
    canvas_draw_str_aligned(canvas, 64, 36, AlignCenter, AlignCenter, furi_string_get_cstr(info));

    furi_string_free(info);

    // Draw controls
    canvas_set_font(canvas, FontSecondary);
    tunerState->isPlaying ? elements_button_center(canvas, "Stop") :
                            elements_button_center(canvas, "Play");
    elements_button_right(canvas, "Note ^");
    elements_button_left(canvas, "Note v");
    elements_button_down(canvas, "Vol v");
    elements_button_up(canvas, "Vol ^");
}

void flipper_tuner_play_tone_scene_on_enter(void* context) {
    App* app = context;
    view_dispatcher_switch_to_view(app->view_dispatcher, FlipperTunerPlayToneView);
}
bool flipper_tuner_play_tone_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}
void flipper_tuner_play_tone_scene_on_exit(void* context) {
    App* app = context;
    if(app->tuner_state->isPlaying) {
        stop(app->tuner_state);
    }
}

static bool metronome_input_callback(InputEvent* event, void* context) {
    App* app = context;

    bool consumed = false;

    if(event->key == InputKeyBack && event->type == InputTypeShort) {
        scene_manager_handle_back_event(app->scene_manager);
        consumed = true;
    }

    return consumed;
}

void metronome_view_draw_callback(Canvas* canvas, void* model) {
    furi_assert(model);
    MetronomeState* metronome_state = model;

    canvas_draw_frame(canvas, 0, 0, 128, 64);
    canvas_set_font(canvas, FontPrimary);

    FuriString* info = furi_string_alloc();
    furi_string_printf(info, "BPM: %d", metronome_state->bpm);
    canvas_draw_str_aligned(canvas, 64, 26, AlignCenter, AlignCenter, furi_string_get_cstr(info));
    furi_string_free(info);
}

void flipper_tuner_metronome_scene_on_enter(void* context) {
    App* app = context;
    view_dispatcher_switch_to_view(app->view_dispatcher, FlipperTunerMetronomeView);
}
bool flipper_tuner_metronome_scene_on_event(void* context, SceneManagerEvent event) {
    UNUSED(context);
    UNUSED(event);
    return false;
}
void flipper_tuner_metronome_scene_on_exit(void* context) {
    UNUSED(context);
}

/// handler arrays must be in same order as scenes enum
// on_enter handlers
void (*const flipper_tuner_scene_on_enter_handlers[])(void*) = {
    flipper_tuner_main_menu_scene_on_enter,
    flipper_tuner_play_tone_scene_on_enter,
    flipper_tuner_metronome_scene_on_enter,
};

// on_event handlers
bool (*const flipper_tuner_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    flipper_tuner_main_menu_scene_on_event,
    flipper_tuner_play_tone_scene_on_event,
    flipper_tuner_metronome_scene_on_event,
};

// on_exit handlers
void (*const flipper_tuner_scene_on_exit_handlers[])(void*) = {
    flipper_tuner_main_menu_scene_on_exit,
    flipper_tuner_play_tone_scene_on_exit,
    flipper_tuner_metronome_scene_on_exit,
};

// scene manager handler object
static const SceneManagerHandlers flipper_tuner_scene_manager_handlers = {
    .on_enter_handlers = flipper_tuner_scene_on_enter_handlers,
    .on_event_handlers = flipper_tuner_scene_on_event_handlers,
    .on_exit_handlers = flipper_tuner_scene_on_exit_handlers,
    .scene_num = FlipperTunerSceneCount,
};

// Handles custom events like timer, GPIO pins
static bool basic_scene_custom_callback(void* context, uint32_t custom_event) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

bool basic_scene_back_event_callback(void* context) {
    furi_assert(context);
    App* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

// Memory allocation
static void play_tone_alloc(void* context) {
    App* app = context;

    app->play_tone_view = view_alloc();

    view_set_draw_callback(app->play_tone_view, play_tone_view_draw_callback);
    view_allocate_model(app->play_tone_view, ViewModelTypeLockFree, sizeof(TunerState));
    app->tuner_state = view_get_model(app->play_tone_view);

    app->tuner_state->currentNoteIndex = 57; // A4
    app->tuner_state->currentNote = tunings[app->tuner_state->currentNoteIndex];
    app->tuner_state->volume = 1.0f;
    app->tuner_state->isPlaying = false;

    view_set_input_callback(app->play_tone_view, play_tone_input_callback);
    view_set_context(app->play_tone_view, app);

    view_dispatcher_add_view(app->view_dispatcher, FlipperTunerPlayToneView, app->play_tone_view);
}

static void metronome_alloc(void* context) {
    App* app = context;

    app->metronome_view = view_alloc();

    view_set_draw_callback(app->metronome_view, metronome_view_draw_callback);
    view_allocate_model(app->metronome_view, ViewModelTypeLockFree, sizeof(MetronomeState));
    app->metronome_state = view_get_model(app->metronome_view);

    app->metronome_state->bpm = 120;
    app->metronome_state->pitch = 57; // A4
    app->metronome_state->isPlaying = false;

    view_set_input_callback(app->metronome_view, metronome_input_callback);
    view_set_context(app->metronome_view, app);

    view_dispatcher_add_view(app->view_dispatcher, FlipperTunerMetronomeView, app->metronome_view);
}

static App* app_alloc() {
    App* app = malloc(sizeof(App));
    app->scene_manager = scene_manager_alloc(&flipper_tuner_scene_manager_handlers, app);
    app->view_dispatcher = view_dispatcher_alloc();

    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(app->view_dispatcher, basic_scene_custom_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, basic_scene_back_event_callback);

    // Submenu view
    app->submenu = submenu_alloc();
    view_dispatcher_add_view(
        app->view_dispatcher, FlipperTunerSubmenuView, submenu_get_view(app->submenu));

    play_tone_alloc(app);

    metronome_alloc(app);

    return app;
}

static void app_free(App* app) {
    furi_assert(app);

    // Remove views
    view_dispatcher_remove_view(app->view_dispatcher, FlipperTunerSubmenuView);
    view_dispatcher_remove_view(app->view_dispatcher, FlipperTunerPlayToneView);
    view_dispatcher_remove_view(app->view_dispatcher, FlipperTunerMetronomeView);

    // Memory free
    scene_manager_free(app->scene_manager);
    view_dispatcher_free(app->view_dispatcher);
    submenu_free(app->submenu);

    view_free(app->play_tone_view);
    free(app->tuner_state);

    view_free(app->metronome_view);
    free(app->metronome_state);
    free(app);
}

int32_t flipper_tuner_app(void* p) {
    UNUSED(p);
    App* app = app_alloc();

    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(
        app->view_dispatcher, gui, ViewDispatcherTypeFullscreen); // Initialize GUI
    scene_manager_next_scene(app->scene_manager, FlipperTunerMainMenuScene); // Begin at main menu
    view_dispatcher_run(app->view_dispatcher);

    app_free(app);
    return 0;
}
